### ISSUE TITLE
1 Test fails

### ISSUE THREAD

**Issue by veritazx** [zms-publishing/Products.ZMySQLDA#15]
There is a failing unicode Test. I wasn't able to fix it. Sorry.

**Comment by dataflake** [comment]
The only failing tests I see are flake8-related formatting issues that I'd like you to fix. Travis shows all other tests passing.

**Comment by veritazx** [comment]
Strange. I get the following Test Output on:
Server version: 10.3.14-MariaDB - Homebrew
Protocol version: 10
Server charset: UTF-8 Unicode (utf8)

Error in test test_manage_test_no_use_unicode (Products.ZMySQLDA.tests.test_DA.RealConnectionTests)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/git/Products.ZMySQLDA/Products/ZMySQLDA/tests/test_DA.py", line 252, in test_manage_test_no_use_unicode
    self.da.manage_test(sql)
  File "/Applications/Plone/zinstance/eggs/Products.ZSQLMethods-2.13.5-py2.7.egg/Shared/DC/ZRDB/Connection.py", line 135, in manage_test
    res=dbc.query(query)
  File "/git/Products.ZMySQLDA/Products/ZMySQLDA/db.py", line 247, in query
    return self._access_db(method_id='query', args=args, kw=kw)
  File "/git/Products.ZMySQLDA/Products/ZMySQLDA/db.py", line 273, in _access_db
    return getattr(db, method_id)(*args, **kw)
  File "/git/Products.ZMySQLDA/Products/ZMySQLDA/db.py", line 531, in query
    db_results = self._query(qs)
  File "/git/Products.ZMySQLDA/Products/ZMySQLDA/db.py", line 491, in _query
    self.db.query(query)
  File "/Applications/Plone/zinstance/eggs/mysqlclient-1.4.2.post1-py2.7-macosx-10.14-intel.egg/MySQLdb/connections.py", line 224, in query
    _mysql.connection.query(self, query)
OperationalError: (1366, "Incorrect string value: '\\xFCbrige...' for column `zmysqldatest`.`test_zmysqlda`.`c_varchar` at row 1")

**Comment by dataflake** [comment]
This works fine in my environment. You may have character set/collation settings in your test database that don't work with these test cases.
